<?php
// Initialize the session
session_start();

// If session variable is not set it will redirect to login page
if(!isset($_SESSION['username']) || empty($_SESSION['username'])){
  header("location: login.php");
  exit;
}
?>

<!DOCTYPE html>
<html>
<head>
  <?php $title = "LauOmb Webserver - Portugal diary";
  include 'head.php'; ?>
</head>
<body>

<?php include 'header.php';?>

<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <h2>My trip to Portugal</h2>
      <h5>A diary of my summer holiday 2018</h5>
      <p>This page is going to contain my experiences from my trip around Portugal during the summer of 2018. Starting and ending in Lisbon, I will make my way by public transport and rental car through the country during a three week trip. I have not really planned anything beforehand, I only booked a couple of Airbnb's. SO pretty much everything is impromptu, let's see what this country has to offer me..</p>
      <p>Here we go!</p>
    </div>
    <div class="card">
      <a name="lisbonone"></a><h2>15-aug 13:45 - The day the adventure started.</h2>
      <h5>You cannot plan for things to happen, so why bother planning anyway.</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Having prepared for the trip for a couple of weeks already, I only had to finish packing my bag in the morning. Wednesday is defintely a weird day to start your holidays.. My parent offered to bring me to the airport, so naturally they were 20 minutes early and I was still running around when they rang the door bell. Anyway, all neccessities are there, let's go! Smooth ride to the airport, in the midsts of all commuters.So long guys, I'm off (silent evil laugh here).</p>
      <p>At the airport everything went smooth as well. Security no issues (how could there be, with this face right, hehe..). Sitting in de Lounge (No 25 apparently) for the first time in my life, I met Chris and John from New Zealand (Wellington). They were on their way back to New Zealand, having visited the Uk and Portugal. Their son lives in the UK, and I offered to give him some tips if he'd ever consider visiting the Netherlands. Of course we had a many things to talk about, like going for the Urban Adventures tour in either Lisbon or Porto. Will check that out when I get to Lisbon, perhaps nice to do with Rebecca and Jeroen. We also discussed how technology changes to rapidly these days (they are a bit older than me), and ended up advising John on which noise cancelling headphones he should buy.. Of course the Bose QC35 Mk II, and he pretty much blindly spent 350 EUR on those babies for his trip to China. After helping also set it up with his phone ("do we have an App for that.., yes we do!") In return we exchanged contact details and agreed to meet again in New Zealand, so I got that covered.. John works at a legal company according to his business card, always good to have those in your network!</p>
      <p>When we said goodbye, my flight departing roughly one hour before theirs, Chris mentioned to me that "your mother should be proud of you being so helpfull to others." There you go mum, you did well ;-). The first experience is in the pocket, and the next one would follow up shortly.</p>
      <p>Boarding the plane is no issue, stuff I'm used to. The priority treatment is nice though, it's a very comfortable way to start a trip. At least as comfortable as flying can be..</p>
      <p>Doors are closed, the security announcement has finished and we are waiting to taxi onto the actual runway when we hear the beep from the internal communication system. No announcement. A couple of minutes later, again the beep. This time it's the captain addressing all passengers. "Ladies and gentlemen. We have just been informed that there is a major issue with the air traffic radion frequencies in the Netherlands. Due to this issue, no air traffic is currently allowed in Dutch airspace. Airborne planes are directed to other countries, and we cannot take off. We can also not go back to the gate as you can see when looking out of the window, we are stuck in traffic.. We will keep you updated along the way, to conserve fuel we have to shut down the engines."</p>
      <p>Well ain't that great.. I should be honest though, actually it put a smile on my face. These things you cannot predict, they just happen and I am just going with the flow. I send a Quick message to the host in Portgual that I'll be arriving later than scheduled and there it is: the second experience of the trip is a fact! The Portugese boy next to me has fallen asleep by now, the girl next to him is furiously looking at her phone as if  she is late for a job interview or something. After some time I bring out my headphones (the Bose QC15, damn the 35 is definitely an improvement!) and listen to some music. Eventually I decide to bring out the laptop and start this diary. And of course, right as I have set up everything... The beep. "Ladies and gentlemen this is your captain again. The issues are being resolved and air traffic control is slowly letting planes depart again. Please return to your seat and bla bla bla.." Lovely, now I need to pack everything again.</p>
      <p>It's now 14:30 and I am truly on my way! Next entry will be from Lisbon. I need to pee but don't want to get up. Do we have an app for this..?</p>
    </div>
    <div class="card">
      <h2>15-aug 23:15 - Apparently getting to Lisbon isn't easy..</h2>
      <h5>It's that, or someone is telling me to take it really slow.</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>First thngs first, I got to tinkle at the airport. The flight was good, nothing special I'd say. It took a while for my bag to arrive so the sticker 'Priority' doesn't help much, but anyway I got my things. I had send a text to Alena from the guest house where I would be staying, nd made my way to the metro..</p>
      <p>And there the second long wait of the day started. With a big bagpack on my back, and the little on on the front, stuffed together as sardines in a can (which by the way is something the Portgual is famous for, as I found out later), it took a mere 40 minutes without the Metro to go anywhere before people gave up. Me included, as the temperature was close to 30 degrees and my legs started to hurt. Ok, what are my options? Train is a no-go, taxi probably a rip off. How about an Uber.. Of course we have an app for that, and as soon as I searched for an Uber I got a phonecall from Mario where he could pick me up. 15 minutes later and six euro's down, I was at the guest house (should have thought about this waaay earlier).</p>
      <p>It's a nice place, basically a huge house where they made six guest rooms, three bathrooms, a common kitchen and living area, and I haven't seen a single sole so far, apart from Alena of course. Switched outfits (shorts!!) and headed out to the waterfront. The sun is pretty strong so bought a hat as soon as I found a souvenir shop, luckily they are everywhere. For some reason I feel a bit like James Bond in Die Another Day, when he is on the beach "for the birds".. But anyway, walked around for quite a bit, took some shots and ended up having dinner somewhere in the middle of the street. A typical Portugese dish called <a href="https://en.wikipedia.org/wiki/Francesinha" target="_blank">Francesinha</a>. It's a kind of sandwich lasagna on a bed of tomato sauce and covered in french fries with an egg on top. Bloody hell that's a lot of food, tasty but way too much for these temperatures!</p>
      <p>Ate as much as I could and by the time I was finished it started to twilight. The 'Castelo de S. Jorge' is nearby, on top of a hill, and I figured I would get a nice sunset from there. Also I could use the excercise to walk off dinner, so headed uphill to try to find the entrance. I found it, had to pay money to get in and the Castle would only be open until 9PM or so, so I ended up walking through all kinds of little streets. Got some really nice scenic photos, and a possible dinner location with a view for when Rebecca and Jeroen are here.</p>
      <p>Back at the appartment I dropped the camera and hat, and headed out again to grab a coffee and enjoy the evening. Completely forgot that it is Wednesday and simultaneously a Bank Holiday, so it isn't very crowded. Enjoying a cappucino and fresh strawberry juice, I am laughing at the little boy at the table next to me trying to devour a plateof really large shrimp. He got as far as breaking the head and legs off, but his parents apparently didn't tell him to peel off the skin as well. By the look on his face I can only confirm that it doesn't taste really good nor is it easy to chew away, hehe.</p>
      <p>I do also realize that I am actually quite tired. Tomorrow another day, it's been quite a long one today anyhow so best to head back. Update the diary, put up some music and go for a shower. Tomorrow maybe I'll go visit the botanical gardens. Seems like a 15 minute walk, that should be do-able I guess. Nighty night!</p>
    </div>
    <div class="card">
      <h2>18-aug 11:50 - See ya Lisbon, hello Porto (part one)</h2>
      <h5>Fast wifi on the train, apres ski music through the speakers!</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>With about three hours to go until I get to Porto, I figured it would be a great chance to update my story. At the moment I am in the train to Porto, with about ten minutes to go. I have to say, although parts of Lisbon look like crap (and smell like crap as well..) this train is supernice. Clean, spacious, wifi (ohw heal yeah!) and a 220v outlet to charge everything. Awesome!!</p>
      <p>So, the last two days were basically all about nothing at all. Sounds logic right? The goal I had set myself was to do as little as possible, and I think it worked out quite well. On Thursday, as written in the previous post, I went to the Botanical Gardens. It was a bit of a walk but right before it got really warm I was covered by trees and enjoying a drink. I had taken a book with me and figured it would be nice to read a few pages to cool down again. Two-thirds of the entire book later I started to get hungry.. Looking at my phone I had at there for a solid seven hours, and in the mean time the second band had set up their equipment and had started with their covers of all kinds of songs. The first artist was a solo-guitarist, and after some good tunes of Bruce Springsteen and Bob Marley I took a few photos. He approached me afterwards and asked if I could send him the photos I made. Sure no worries, but he would have to wait to somewhere in September, after I had gone back home. That was no issue for him and so another email address was exchanged. What a great day to do nothing, also I managed to slowly adapt to the sun, without buring my skin right the first few days.</p>
      <p>I walked back to the main square (still have to look up the name..) and decided I would go for Italian tonight. Of course nowhere near a Portugese dish but there is plenty of time. The temperature shifts quite dramatically between day and evening, as there is a seawind (I guess) that picks up around 6:00PM. Since I have nothing long-sleeved with me, at around 9:30PM it actually gets chilly. Decided to finish the book I started, the adventures of Robert Langdon remain interesting and it's a great read! Last thing I ordered at the restaurant was a customized ice cream: two scoops of ice cream and fresh strawberries. My gosh it took a solid twenty minutes to finsh that bowl of ice cream.. The food is slightly cheaper in Portgual, as the portions are quite big for the money you pay for it.</p>
      <p>Back in the Guest House I took a shower in one of the three bathrooms. They are great to see, all kinds of different mosaics and colors make it a great sight. Even for a color blind person ;-). Time for bed, tomorrow I'll try to visit the Castle of S. Jorge, where I was yesterday at the end of the day. That should be nice a nice viewpoint on the city..</p>
    </div>
    <div class="card">
      <h2>18-aug 12:25 - See ya Lisbon, hello Porto (part two)</h2>
      <h5>Fast wifi on the train, apres ski music through the speakers!</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Alright, Friday it is. Time to visit a castle. Breakfast in one of the main streets, where yesterday I went for bacon and eggs, today a toasted sandwich with way too much ham, and a croissant. Accompanied by what only can described as a candidate for the worst coffee with milk ever, I decided to try to find the castle whilst avoiding most of the tourists. Bought a big bottle of water and set off, the climb to the hill had to be finished before noon.</p>
      <p>Well I made it to the entrance of the castle, but a visit would not be happening today.. The queue to get a ticket was as long as the train I am currently in, and I can tell you that it's quite a long train. So, different plan, let's try to walk around the entire hill that the castle is build on, to see if I can find another viewpoint of some sorts. Then I'll just imagine the castle towers (there is probably a VR app for that..). So I started to wander around and I can tell you, that did not disappoint at all. I found quite a few nice spots, and some seriously nice panoramic views of the city on the other side of the hill (other side as in opposed to the view towards the part of the city where I was staying). One site was some kind of playground for kids, where  I made a photo and send it to the folks back in Holland. Antoher was next to another church (there's quite a few in Lisbon). with a small bar nicely shaded by trees. Wanted to get a beer there and enjoy the view,  appareantly there are quite few places in Portugal where you can only pay with cash. Me being the ubernerd I obviously didn't have any cash with me so I needed to find an ATM. Back to the terrace with cash, and the second of three books I brought with me on this trip. This one is a bit more difficult to read, Lolita in some kind of semi-poetic English.. Anyway, two beers down I decided to slowly head back down and back to the main square again, I think it was around 6:00PM again.</p>
      <p>Note to self: this is going like clockwork..</p>
      <p>Not being hungry when I get back to the square, I decide to sit down in the shade. Find a spot and as I come to learn in a few minutes, the spot I selected is the starting point of the Free Lisbon Tour. There is a large group of people listening to Raffa, who is rambling on about most likely the history of Lisbon. Everything being in Spanish or Portugese I understand nothing at all, so I decide to focus on visual rather than audio. Interestingly enough, there is a group of around seven drug dealers constantly walking around the square selecting possible buyers of hash, coke or whatever other types of narcotics they havewith them. Seriously, with the police on two corners of the square actively looking around, they have nerves these guys. Or perhaps the police allows it, as at least three of the guys are dressed in the most obvious of ways, a black shabby suit with identical hats. It doesn't even take a trained eye to spot them, any eye would be able to identify them in 20 seconds. The other four guys seem to be the 'management' as they kind of control the suited guys and sell simultaneously. I guess they are not making a large profit tonight, none of the attempts they make seems to transition into an actual transaction. Too bad guys..</p>
      <p>Tonight I would go for a more traditional dish: Paella. Not sure if it is Spanish or Portugese, but you can get it everywhere here so it must be somewhat local at least. No fish yet, safely chose the cicken version :-). Very tasty dish, this one is a keeper! I'll go back to the Guest House a bit earlier, I need to pack my stuff.</p>
    </div>
    <div class="card">
      <h2>18-aug 12:55 - See ya Lisbon, hello Porto (part three)</h2>
      <h5>Fast wifi on the train, apres ski music through the speakers!</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Woke up quite early but well rested. The quiet times in the kitchen area are until 10:00AM so I need to make as less noise as possible with my backpacks.. Went to Nicolau, a nice looking place I spotted while walking back to the Guest House the evening before. Went for a hummus-avocado sandwich and a maple syrup pancake. Ohw why the hell not right.. Ok so we will be going back to this place with the three of us, provided we are near the place in a few weeks. Some damn tasty food that was! After sitting there for about an hour or so, packed up my bags again and made my way to the train station. Alena gave me the tip to take the metro, but as sporty as I am feeling I decided the good ol' legs could do the same. It took a bit longer than the metro obviously but I made it, navigating this city is very easy!</p>
      <p>Not much to do at the trainstation itself and I had more than an hour to spare, so figured I could sit outside for a bit. Found an empty bench of which the backside was put against another bench where two men were engaged in a heavy discussion. Sat down but after thirty seconds or so found out that the two men were homeless, bloody hell what a smell! I'll spare you the details but it was all but fresh. I managed to remain seated for five minutes but then hurried up back to the trainstation as I couldn't stand it anymore.. Sat down for a bit until it was time to board the train. Bought a bottle of water to bring on the train and found my seat.</p>
      <p>So that's where I am now. Next to me is a Russian guy, together with his partner, a little kid and a baby that is constantly smiling at me when I look over. Behind me is a young couple who are going to be thrown out at the next stop as they didn't buy a ticket (or at least not the correct ticket) and the carriage that I can see through the door houses the bar. Is it time for a beer already? Mwoah, 1:15PM is a bit early I'd say.. Ok maybe some water to accompany an episode of Breaking Bad then, for which I found out yesterday evening that the last season is not on Netflix..</p>
      <p>Outside the dry (but somehow still green) countryside of Portugal is every now an then interrupted by a city. White houses with red roofs, a very occasional swimming pool and quite a few wineries alternate each other. Outside temperatures easily reaching 34 degrees, a twelve degree difference with the carriage. Next stop: Porto!</p>
    </div>
    <div class="card">
      <h2>19-aug 22:45 - title</h2>
      <h5>subtitle</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Saturday - arrive in Porto, take the metro, received by vava, nice appartment, change clothes and walk around, text from vava with all kinds of restaurant tips, agree to go for a drink, eventually don't go for drinks, dinner at mexican place</p>
      <p>Sunday - next day decide to go to the beach, buy some groceries and walk to metro again, meet older (dutch) couple walking the camino, great conversation; they advise me to go without technology ("if you want it you can do it"), get to the beach, very nice, pretty warm, water is freezing cold, spend entire day there, putting on sunblock is tricky (need to buy more), on the way back text vava to go for drinks, new time set 7PM, take a shower and wash a few shirts, meet VáVá and friend (and dog: Augusto) for drinks and a good conversation, we also talk about work, friend works for Johnson and Johnson and she knows all about the American culture at big organizations, we also talk about differences between dutch and portugese culture (dinner is after the sun is down, no one pulls agenda's to meet up, people just call each other impromptu, etc.), food for thought.., after the drink walk around a bit and go for dinner at brazilian place recommended by vava, walk back through some streets, atmosphere of the city in the evening is very relaxing. Slightly burned from the sun</p>
    </div>
    <div class="card">
      <h2>22-aug 20:30 - title</h2>
      <h5>It's all about Port in Porto in Portugal</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Monday - Since shoulders hurt a bit, rent a bike and go cycling. Go up river, very easy to cycle here. Find a nice spot where locals are swimming, should have brought shorts. Go back to the city, cross the bridge and cycle uphill to look at some wine cellars. Lots of nice little streets, in the end go to the last bridge closest to the sea. A lot of fishermen here. Take some nice photos and go back since temperature is quite high. Walk back to appartment and go for dinner in a local place. Five euro's for an entire meal, nice! Then walk around a bit and buy a little box of mints, a new collection is started!</p>
      <p>Tuesday - Beach again, this time a lot better with surf shirton. Temperature is also a lot better. Dinner was Italian</p>
      <p>Wednesday - Go for a walk across the bridge and enjoy my first glass of Port. Eventually decide to go for a Port cellar visit and taste at Sandeman. Tasted a white port, a ruby and a tawny. Buy for 50 euro's of Port to enjoy at home and walk around. Eventually cross the bridge again and after a long sit at the waterfront go for ice cream. Huge line at some old book store. Then a lot of sirenes and four firetrucks and huge amount of police show up. After a while everybody leaves again, nothing happened. Now on my way to dinner.</p>
    </div>
    <div class="card">
      <h2>23-aug 20:30 - title</h2>
      <h5>subtitle</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Dinner Wednesday ended up being Italian. Had to make a reservation at 10PM, great calzone pizza. Then a walk around and that's about it.</p>
      <p>Thursday - It's a bit chilly this morning, very cloudy as well. Had to do laundry, a lady at the laundry place helped me to understand the process as pretty much everything is in Portugese. Laundry took an hour or so, after which I had lunch (skipped Breakfast) at the Epoca place nearby the appartment. The sun came out which was nice, went for another walk through the city, not much else planned to do. Sat down by the river and ended up on the terrace with another glass of Port. Went back home eventually and prepped a bit more for the trip. The Avis place is actually quite closeby so that will come in handy tomorrow when picking up the car. Need to do a lot of driving the first day so should leave on time.</p>
      <p>Went for dinner at some hamburger place, close to the Italian restaurant of the day before. It was very busy at the place, people were lining up outside so I didn't stay long and decided to go for a walk to the river. Realizing this would be my last walk in Porto for while (if not ever..). It was quite cold again, there was some sort of fog that was passing through the city. You could see it when looking into a street light for example. Anyway, made my way down and along the way I stopped a few times to listen to the street artists and bands that you can find everywhere in Portugal. There is people playing a guitar, a harmonica, one-man bands, duo's of violins and cello and complete bands with sitar, bass vocals and what not. Some play instruments that consist out of empty paint buckets and random pieces of metal, others play highly modern and minimalistic designer-instruments. Some are better than others obviously, but all together it would sure be a thing to remember.</p>
      <p>Down by the river side there was a young guy playing a keyboard. It was kind of sad music and he seemed very sad as well, made me feel a bit melancholic. Although the last few days I might not have realized it much, walking around and letting my mind go everywhere did get something out of my system.. Soon I would be with people I know again, in places that I recognize and stuff. It's a good thing, don't get me wrong here, but it's just that the anonymity is something that I will leave behind. I guess it was way too long since I had been on my own like this, in another place in another country even.</p>
      <p>I listened to the guy for a while, what amazed me was that he was able to check his phone for messages while playing.. Then I walked along the boulevard and stopped by a few other artists. Eventually I turned around as I was almost at the bridge (which is the end of the boulevard) and slowly walked back. It is less cold down here than it is uphill, which feels strange as I am closer to the water and would have thought that it is the water that influences the temperature. Anyway, it's time to go back and start packing for real. I take a few more photos, suck in the sight of the riverside with the port houses on the other bank, and start walking back uphill through the streets. I continue to hear the sad piano guy playing his tunes up to at least three to four blocks uphill, which is quite a distance and there are cars and noisy tourists with screaming kids all around the city.. The city is different by night. It is now around 10:30PM but if you look at what is going on and the amount of people (and kids) outside you would say it's 7PM or so. There are families everywhere, half of them are still having dinner somewhere, the other half are just walking around like me. The occasional homeless guy sleeping on a corner, another corner occupied by a drugs dealer (yes you have them here as well).</p>
      <p>I get back to the part where the appartment is. It's definitely colder here, but passing by the Clérigos Tower I hear some music coming from the roof of a small shopping mall. I walk up and find a bar here, that I had never spotted nor heard before. And I walked by this place pretty much every day.. I take a quick look but decide not to go for a drink. After all, no one to share the drink with. That's another thing I realize just now. Traveling by yourself is great to clear your mind, but there is a reason why after I came back from my world trip I told myself that I wanted to travel with someone.. Most of the time I spend in Porto I was on my own. The only exceptions were the drink with VáVá and her friend, and the group of people during the Port cellar visit. My mind is going everywhere these days, there is so much that comes to mind when I am forcing myself not to think about work. It might sound stupid but thinking about work is easy, at least a lot easier to deal with than all the other stuff.. Well, all the other stuff is exaggregating, it's just being on my own that is difficult.</p>
      <p>So there is positives and negatives to this trip, like with everything I guess. It's not good, it's not bad, it just is.</p>
      <p>Crossing one of the last squares, I decide to walk around the hospital as there is a viewpoint that I would like to visit one more time. I turn the corner and there is piano music playing from the Moroccan sisha bar in the street. It actually sounds a bit like the music the guy at the riverside was playing, what a coincidence..The wind is picking up, now I start to get cold and I increase my pace. I actually missed the viewpoint but I only realize this when I am already back at the appartment. And as I say in such occasions: something to do when I come back next time (not knowing if there will ever be a next time). It's time to pack. Officially tomorrow I will leave Porto, but actually this evening I kind of said my goodbye already. It remains weird, how easy it was to say goodbye to Lisbon, how sad it makes me feel, leaving Porto..</p>
      <p>Hope to see you again. To breathe in the atmosphere of this historical place, to listen to the artists who try to make a living out of anything, to enjoy the cheap but great food at places where the locals go. Até logo!</p>
    </div>
    <div class="card">
      <h2>date time - title</h2>
      <h5>subtitle</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Friday: pickup car, pay extra for toll road machine, drive to Figueira da Foz for lunch, really good fish, continue to Milfontes but go via highway due to limited time, actually nice to have the toll machine, get there around 6PM, meet Ina, there is a BBQ that evening that I could join, get groceries (hamburger), meet up at the BBQ, there is an entire family there (the people who own the hostel), also neighbours from down the street join, meet Leila from Bern Switzerland, talk a lot with Pedro who has lived in the Netherlands for 6 years, we all eat together and share food, good atmosphere, talk about traveling; food; people; history of Portugal, shower around midnight, actually staying in the same room as Leila, also two Italian girls but they don't say much, decide to visit the beach the day after</p>
      <p>Saturday: early wake up as the Italian girls make a lot of noise when they decide to repack their entire backpacks.., talk to Leila and end up visiting some beaches with her, hike along the dunes and have a salad for lunch (in the bag the lettuce came in, big mess), collect sand sample for back home and relax, we talk a lot, Leila studies psychology so great talks, drop Leila off at busstop and go back to hostel, meet Claudia (Brazilian) and Sonia (Portugese), two friends that travel together, they are now staying in the room with me, decide to make dinner together and also to hang out in Lisbon as that is where they live, also in the room is a German girl Catherine, in the evening also meet two Dutch boys and hang out and drink all the beer we have, there are crickets running around that we try to kill</p>
      <p>Sunday, the crickets ate each other so they are gone, Sonia, Claudia and I pack our bags and Sonia makes breakfast, I wake up Claudia which went funny, When in the kitchen meet a Romanian couple of which the lady is working at UIPath, with the girls decide to hit a few beaches, Praia do Farol and Praia Almograve, at Farol Sonia and I swim to island, when trying to go back to the beach tides comes in and Sonia cannot make it back, I hurt my legs and feet rescuing Sonia, eat home made lunch at the beach then continue to Almograve, great day and a lot of fun with the ladies, get in the car and drive to Aljezur, find the Mayla Surf House, hilly area to get there; nice roads to drive, go for a shower at the hostel, a lot of Germans here and they keep to themselves only, after shower go to get groceries because another BBQ, prepare the burgers and there is a big fight going on between two German guys, bit weird.., end up eating dinner with only one other guy, staying in a room with three German girls, South Korean guy also in the room, offers meto use his Bepanthem cream for my legs</p>
      <p>wake up with rain, make breakfast, bread of the day before hs gone bad already so need to figure out something else, glass of milk is nice, the SK guy is desperately looking for a ride but don't want to hang out with him, go to pharmacy to buy cream, then decide to visit the fortress but cannot find the route so end up at Amoreira beach, quite nice so stay there for a bit, turn around and go back for lunch at the fortress but again miss the exit and end up at Monte Clerigo beach, when at a viewpoint hear a Dutch ouple talk about my sunblock and engage in onversation with them, Anne and Jitske are form Friesland and we go have lunch at Taberna do Gabriel II, thisplace overlooks Amoreira beach and the view is great, the place looks Austrian but the waiter is eastern European, end up eating swordfish which is really good, we sit and talk for a few hours and decide to do a Tikkie on the bill (because we can), say goodbye and drive to Arrifana beach on the way to the hostel, buy some more groceries, there will be salad for dinner, put my photos on the computer and create/update phone diary, fortress is going to have to wait for tomorrow</p>
      <p>Tuesday: wake up with cloudy weather, visit the fortress, not too special actually, go to the city and try to park in Aljezur and end up at supermarket because very crowded, walk around to find a souvenir, have coffee near the creek (formerly a river), decide to buy a funny hat as reminder, take a drive to Pedra da Agulha but turns out to be completely off road, scratch the car quite a bit, eventually find a viewpoint but unable to drive to the actual beach, turn around to go for a swim, want to go to Monte Clerigo but mistakenly drove to Arrifana, relax at the beach, text with Leila, tide is coming in so have to build a dam to protect my stuff, eventually go back to hostel for a shower, want to have Italian dinner and get a recommendation fromsome guy, first buy breakfast in Aljezur and then drive to Arte Bianca, have a great pizza and a glass of wine, the twilight has started so drive to Arrifana beach to see the sun set completely, very peacefull atmosphere, eventually drive back to hostel and relax a bit, german family now staying in my room which is weird</p>
      <p>Wednesday: have breakfast and take off to Sagres, visit lighthouse, fort beliche, walk down a path, fort Sagres which is big but not too special, text aljezur tips to Sonia, have lunh in Sagres and coincidentally run into guy from the BBQ in Villa ova de Milfontes, tell him about the swimming at Farol and he tells me it is one of the most dangerous places to go swimmig because of the currents of the ocean and river meeting there, people frequently drown or need to be rescued by boat because of the situation, drive to Lagos, find the Airbnb eventually, go to the beach (Dona Ana) and go for a swim, water is really nice, borrowed an umbrella from Airbnb but too much wind so don't use it, go to boulevard, try to book cave tour (recommendation fro Anne and Jitske) but there is no operator who would take only one person, go back for shower eventually, there is a festival that evening so go there, eat churros andsitdown atthe stage, quite old outside and a bit of wind, don't have long sleeved clothes with me so use towel as cape, takes forever for the music to start, first some fashion show not too interesting, eat a bread with meat which is nice, music isn't that great either so when I got really cold decide to walk back, the bed actually has no blanket, just the sheets you put around the blanket</p>
      <p>Thursday: wake up and have breakfast from Airbnb (included in price), go to Benagil to visit a cave (recommendation from Sonia), very small beach and already crowded but book a cave tour at 10:30, really nice cave tour, very pretty sights from the water, spot a nice beach during the tour and decide to visit that beach for a swim (Albandeira), drive to the beach through very upstate environment, beach is nice have a spot under the shelter of a cave, drive to Alvor for lunch, then continue to Mei Praia for another swim, watch the sunset, go to appartment for shower and sushi for dinner, walk back to appartment andstop at some street artists, when back have to pack my bag and go for a shave, text a bit with Sonia</p>
      <p>Friday: wake up but there is no breakfast yet, wash and bursh teeth and then have breakfast, young german couple also staying in the house so we eat together, pack all stuff in the car and take off, wonder if anything will be said about the damage to the car from the off road trip, drive to lisbon in one go; stop for gas a few times, toll is quite expensive; around 25 euros for 300 km, quite complicated to find the rental return place, following a car that went the wrong way (good luck with that), very busy at the return point and there is only one guy doing inspections so car doesn't get inspected at all (luckily), go to a bistro and have a coffee, very warm outside and many people are smoking and drinking already.., eventually go back inside and wait for Rebecca and jeroen, when they arrive take the metro to the appartment, have to walk up quite steep with backpack so very warm, appartment is nice, received by Patricia, she shows around, leaves but forget agenda so comes back after a while, rebecca and jeroen share the news, decide to get some groceries for the weekend at oriental supermarket, very smelly in the supermarket, drop the groceries and go to a square nearby, live music at the square of a good band, have food from an Indian guy, he is really nice and makes a lot of jokes, go back to appartment and turn on all fans, sit outside a bit in the nice little street, back inside and go to sleep, sleeping in the lower bunk, jeroen is in the upper bunk and rebecca has the big bed for herself, text with ria on the fifth of september</p>
      <p>Saturday: wake up and go for shower, go for breakfast at nicolau, waitinglist but quick to sit down, have brunch which is a lot of food, then walk around a bit, visit the viewpoint I went to earlier and sit there to enjoy the scenery, have some good conversations, walk back to the waterfront and sit down for a drink at a bar, go back to appartment and find a place to go for dinner, walk up the hill and have dinner at Cozinha Urbana, really good hamburger (bit Japanese style) at a lovely place with some cats around, when dark go back to the appartment and play boerenbridge</p>
      <p>Sunday: wake up and shower, walk to the castle, have breakfast halfway, catle queue is really long again so decide to just walk, go to another viewpoint I had been before, no wind today so even hotter than yesterday, go to commercial square to look at the drug dealers and have a drink (strawberry, lemon, basil juice), go to the subway and go to Rato station to meet with Sonia and Claudia, visit Mercado do XXX and have lunch there, really good food and really great to see the girls again, great conversations and a lot of laughs, go to LX Factory for drinks, with Jeroen and Claudia in an Uber, Rebecca and Sonia with Sonia's car, local market at LX, buy portugese tile coasters, visit alternative bar thing and havea great view of the city (under the bridge), go back for a drink at another place, end up with cocktails, the ladies offer to pay and then have to leave but we get another tip on dinner, we say goodbye and take an Uber to Santa Apolonia station, really funny Uber driver, get to the italian place and have a great pizza, go back to the appartment and play more games, check in for our flight and arrange to sit next to each other (row 11 A,B and C), pack our bags and go to bed</p>
      <p>Monday: wake up and shower, finish packing and go for brunch at Nicolau, decide to split a few menu'sbecause other day too much food, then walk around a bit(with all our stuff, quite heavy) and then take subway to airport, check in my bag (priority so can skip the really long queue) and go through customs, go to toilet and then starbucks for coffee, takes forever to get coffee as the guys are really slow, then sit down at some gate as very busy in the main hall, go to gate and go to the priority boarding queue to secure an overhead luggage bin, board the plane and when airborne update laptop diary, </p>
    </div>
    <div class="card">
      <h2>date time - title</h2>
      <h5>subtitle</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>text</p>
    </div>
    <div class="card">
      <h2>date time - title</h2>
      <h5>subtitle</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>text</p>
    </div>
  </div>
  <div class="rightcolumn">
    <?php include 'portugalside.php';?>
    <?php include 'social.php';?>
  </div>
</div>

<?php include 'footer.php';?>

</body>
</html>
